FROM maven:3.3-jdk-8
EXPOSE 8080
VOLUME /tmp
RUN mkdir -p /usr/src/app
WORKDIR /usr/src/app
ADD . /usr/src/app
RUN mvn install
ENTRYPOINT ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/usr/src/app/target/backstrc-0.0.1-SNAPSHOT.jar.jar"]